version: '3.8'

services:
  # Servidor web
  web:
    container_name: web
    image: nginx:latest
    ports:
      - '8080:80'
    links:
      - 'php'
    volumes:
      - ./src:/var/www/html  # Asegúrate de que esta ruta es correcta
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # PHP
  php:
    container_name: php
    build:
      dockerfile: Dockerfile-php
      context: .
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb

  # Servicio de MariaDB
  mariadb:
    container_name: db
    image: mariadb:10.9
    ports:
      - '8306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - './mysqldata:/var/lib/mysql'

  # Adminer
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    restart: always
    ports:
      - 7777:8080  

# Volúmenes
volumes:
  mysqldata:
